### ISSUE TITLE
Second nanoleaf Canvas is not showing

### ISSUE THREAD

**Issue by Timescape1979** [raepple/nanoleaf-binding#5]
hello, i binded 1 of my 2 canvas installations after some time getting an authentication token. but the second Controller with 15 lightsquares is not shown nor can i set him manually. is there any Chance to get this solved?

some part of the GitHub log

2019-10-09 18:27:31.092 [WARN ] [al.handler.NanoleafControllerHandler] - Cannot send authorization request to controller: 
java.util.concurrent.ExecutionException: java.net.NoRouteToHostException: No route to host
	at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:118) ~[?:?]
	at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:101) ~[?:?]
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:684) ~[?:?]
	at org.openhab.binding.nanoleaf.internal.handler.NanoleafControllerHandler.runPairing(NanoleafControllerHandler.java:353) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at org.eclipse.jetty.io.SelectorManager.doFinishConnect(SelectorManager.java:351) ~[?:?]
	at org.eclipse.jetty.io.ManagedSelector.processConnect(ManagedSelector.java:185) ~[?:?]
	at org.eclipse.jetty.io.ManagedSelector.access$1200(ManagedSelector.java:60) ~[?:?]
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.processSelected(ManagedSelector.java:455) ~[?:?]
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:325) ~[?:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:357) ~[?:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:181) ~[?:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) ~[?:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) ~[?:?]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) ~[?:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762) ~[?:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680) ~[?:?]
	... 1 more

**Comment by stefan-hoehn** [comment]
@Timescape1979 
I only joined the binding team lately and worked a lot on the canvas. I have several canvas myself and I can at least assure you with the current 2.5.2 (and 2.5.3) it works pretty well with multiple controllers. Can you please give it a try again and upgrade to at least 2.5.2 (not sure if 2.5.3 is already out by the time of writing) and can come back to me?

Stefan

**Comment by stefan-hoehn** [comment]
I would assume that this is fixed by now. Closing.
